set -e
for i in "FRIENDLY_LOC_ATTACK_WEIGHT" "ENEMY_ATTACK_HP_WEIGHT" "ADJACENT_ENEMY_ATTACK_WEIGHT" "ADJACENT_FRIENDLY_ATTACK_WEIGHT" "NEARBY_TROUBLED_ENEMY_ATTACK_WEIGHT" "NEARBY_TROUBLED_FRIENDLY_ATTACK_WEIGHT" "ATTACK_IN_FUTURE_MOVES_WEIGHT" "MULTIPLE_ATTACK_WEIGHT"; do python2 rgtuner.py $i $@; done
